{
 "title": "Dash",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values({service_name=\"$app\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(system_cpu_usage{service_name=\"$app\"}) by (instance_name)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{service_name=\"$app\"}) by (instance_name) + sum(jvm_memory_used_bytes{service_name=\"$app\"}) by (instance_name)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "round(sum by(method,uri)(increase(http_server_requests_milliseconds_count{service_name=\"$app\", uri!~\".*actuator.*\", uri!=\"/**\"}[$__rate_interval])))",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": " sum by (method, uri) (rate(http_server_requests_milliseconds_count{service_name=\"$app\"}[1m]))",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_sum{service_name=\"$app\"}[$__rate_interval])) by (method, uri) / sum(rate(http_server_requests_milliseconds_count{service_name=\"$app\"}[$__rate_interval])) by (method, uri)",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  }
 ]
}